export const recentRent = [
  {
    id: 1,
    title: "Downtown Cozy Apartment",
    imgUrl: "/P_01.jpg",
    desc: "Cozy 2-bedroom apartment in the heart of downtown with a modern kitchen and spacious living room.",
    location: "New York, NY",
    Beds: 2,
    Baths: 2,
    Price: 2200,
  },
  {
    id: 2,
    title: "Luxury City Condo",
    imgUrl: "/P_02.jpg",
    desc: "Luxury condo with breathtaking city views, high-end finishes, and access to exclusive amenities.",
    location: "Los Angeles, CA",
    Beds: 3,
    Baths: 3,
    Price: 3500,
  },
  {
    id: 3,
    title: "Spacious Family Home",
    imgUrl: "/P_03.jpg",
    desc: "Spacious family home with a large backyard, perfect for gatherings and relaxation.",
    location: "Austin, TX",
    Beds: 4,
    Baths: 3,
    Price: 2800,
  },
  {
    id: 4,
    title: "Modern Smart Studio",
    imgUrl: "/P_04.jpg",
    desc: "Modern studio apartment with smart home features and easy access to public transport.",
    location: "Chicago, IL",
    Beds: 1,
    Baths: 1,
    Price: 1500,
  },
];

export const recentOffers = [
  {
    id: 1,
    title: "Charming Home Discount",
    imgUrl: "/P_05.jpg",
    desc: "Limited-time offer: Buy this charming home and get a 5% discount on closing costs!",
    location: "San Francisco, CA",
    Beds: 3,
    Baths: 2,
    Price: 650000,
  },
  {
    id: 2,
    title: "Beachside Villa Deal",
    imgUrl: "/P_06.jpg",
    desc: "Special deal on this beachside villa—free furnishing package included!",
    location: "Miami, FL",
    Beds: 5,
    Baths: 4,
    Price: 1200000,
  },
  {
    id: 3,
    title: "Luxury Penthouse Offer",
    imgUrl: "/P_07.jpg",
    desc: "Exclusive listing: Get a luxury penthouse with a complimentary car garage.",
    location: "Seattle, WA",
    Beds: 4,
    Baths: 3,
    Price: 950000,
  },
  {
    id: 4,
    title: "New Townhouse Pre-Launch",
    imgUrl: "/P_08.jpg",
    desc: "Hot deal! Get a newly built townhouse with a 10% discount on pre-launch bookings.",
    location: "Denver, CO",
    Beds: 3,
    Baths: 3,
    Price: 500000,
  },
];

export const recentSale = [
  {
    id: 1,
    title: "Scenic Country Home",
    imgUrl: "/P_09.jpg",
    desc: "Beautiful country home with stunning landscape views and a private garden.",
    location: "Nashville, TN",
    Beds: 4,
    Baths: 3,
    Price: 450000,
  },
  {
    id: 2,
    title: "Urban Loft Apartment",
    imgUrl: "/P_10.jpg",
    desc: "Modern loft-style apartment in a prime location, ideal for urban living.",
    location: "Boston, MA",
    Beds: 2,
    Baths: 2,
    Price: 600000,
  },
  {
    id: 3,
    title: "Luxury Beverly Hills Mansion",
    imgUrl: "/P_11.jpg",
    desc: "Luxury mansion with a private pool, theater, and state-of-the-art security.",
    location: "Beverly Hills, CA",
    Beds: 6,
    Baths: 7,
    Price: 5000000,
  },
  {
    id: 4,
    title: "Charming Portland Bungalow",
    imgUrl: "/P_12.jpg",
    desc: "Charming bungalow in a quiet neighborhood, perfect for first-time homebuyers.",
    location: "Portland, OR",
    Beds: 3,
    Baths: 2,
    Price: 350000,
  },
];
